### ISSUE TITLE
Only columns may be immediate children of rows

### ISSUE THREAD

**Issue by fabrice102** [kaymckelly/freelance-iacr#121]
Thanks for your template! Here is a minor comment about it.

According to bootstrap documentation and bootlint (<https://github.com/twbs/bootlint>), only columns may be immediate children of rows. But `<header>` is not a column but still is an immediate child of a row.

Similarly, any column must be a child of a row.

Here is a possible fix:

Change the html to:

```html
      <header id="conf_id" class="row headerImg">
        <div class="col-sm-12 headerGradient">
          <div class="row">
            <div class="col-sm-6">
              <h1 class="headerTitle">
                <span class="conf_name"></span>
              </h1>
            </div>
            <div class="col-sm-6">
              <h3 class="headerInfoTop">
                <span class="conf_dates"></span>
              </h3>
              <h3 class="headerInfoBottom">
                <span class="conf_location"></span>
              </h3>
            </div>
          </div>
        </div>
      </header>
```

Change the `.headerImg` css (`styles/main.css`) to remove `width: 100%`:

```css
.headerImg {
  background-size: cover;
  background-image: url("../images/defaultbg2_crop.jpg");
  background-position: center center;
  height: 240px;
}
```
